server:
  port: 8080

spring:
  application:
    name: catalog-service
  profiles:
    active: dev
  config:
    import: configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      retry:
        enabled: true
        max-attempts: 12
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh