apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: catalog-service }
  template:
    metadata:
      labels: { app: catalog-service }
    spec:
      containers:
        - name: catalog-service
          image: docker.io/celalcagri/catalog-service:amd64
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: SPRING_CLOUD_CONFIG_FAILFAST
              value: "true"
            - name: SPRING_CLOUD_CONFIG_RETRY_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "12"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "1000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER
              value: "1.5"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL
              value: "5000"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector: { app: catalog-service }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: catalog-service
spec:
  to: { kind: Service, name: catalog-service }
  port: { targetPort: http }
  tls: { termination: edge }